# Generated by Django 5.2.7 on 2026-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferide_backend', '0004_violation_license_plate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
